-- SmartAttend Neon schema draft.
-- This file is intentionally not applied automatically because DATABASE_URL was not configured.

create table if not exists organizations (id text primary key, name text not null, plan text not null default 'Campus Plus', created_at timestamptz not null default now());
create table if not exists users (id text primary key, organization_id text not null references organizations(id), name text not null, email text not null unique, role text not null check (role in ('student','teacher','admin')), department text, disabled_at timestamptz, created_at timestamptz not null default now());
create table if not exists departments (id text primary key, organization_id text not null references organizations(id), name text not null, created_at timestamptz not null default now(), unique (organization_id, name));
create table if not exists courses (id text primary key, organization_id text not null references organizations(id), code text not null, name text not null, department_id text references departments(id), teacher_id text references users(id), status text not null default 'active' check (status in ('active','archived')), created_at timestamptz not null default now(), unique (organization_id, code));
create table if not exists classes (id text primary key, organization_id text not null references organizations(id), course_id text not null references courses(id), room text not null, starts_at timestamptz not null, ends_at timestamptz not null, status text not null default 'scheduled' check (status in ('scheduled','live','closed','expired')), created_at timestamptz not null default now());
create table if not exists class_enrollments (class_id text not null references classes(id), student_id text not null references users(id), created_at timestamptz not null default now(), primary key (class_id, student_id));
create table if not exists attendance_sessions (id text primary key, organization_id text not null references organizations(id), class_id text not null references classes(id), teacher_id text not null references users(id), status text not null default 'draft' check (status in ('draft','active','closed','expired')), started_at timestamptz, closed_at timestamptz, created_at timestamptz not null default now());
create table if not exists attendance_challenges (id text primary key, organization_id text not null references organizations(id), session_id text not null references attendance_sessions(id), code_hash text not null, expires_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists attendance_records (id text primary key, organization_id text not null references organizations(id), session_id text not null references attendance_sessions(id), student_id text not null references users(id), status text not null check (status in ('present','late','absent','pending','flagged')), confidence integer not null default 0, verified_at timestamptz, device text, created_at timestamptz not null default now(), unique (session_id, student_id));
create table if not exists attendance_verifications (id text primary key, organization_id text not null references organizations(id), attendance_record_id text not null references attendance_records(id), challenge_id text references attendance_challenges(id), method text not null, result text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists devices (id text primary key, organization_id text not null references organizations(id), student_id text not null references users(id), label text not null, fingerprint_hash text not null, trusted boolean not null default false, last_seen_at timestamptz, created_at timestamptz not null default now());
create table if not exists suspicious_attendance (id text primary key, organization_id text not null references organizations(id), attendance_record_id text not null references attendance_records(id), reason text not null, status text not null default 'open' check (status in ('open','approved','rejected')), reviewed_by text references users(id), reviewed_at timestamptz, created_at timestamptz not null default now());
create table if not exists notifications (id text primary key, organization_id text not null references organizations(id), user_id text not null references users(id), title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists attendance_policies (id text primary key, organization_id text not null unique references organizations(id), late_after_minutes integer not null default 10, challenge_ttl_seconds integer not null default 30, require_trusted_device boolean not null default true, updated_at timestamptz not null default now());
create table if not exists audit_logs (id text primary key, organization_id text not null references organizations(id), actor_id text references users(id), action text not null, target text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index if not exists users_organization_idx on users(organization_id);
create index if not exists courses_organization_idx on courses(organization_id);
create index if not exists classes_organization_idx on classes(organization_id);
create index if not exists attendance_records_organization_idx on attendance_records(organization_id);
create index if not exists notifications_user_idx on notifications(user_id, created_at desc);
create index if not exists audit_logs_organization_idx on audit_logs(organization_id, created_at desc);
